name: 'Build Docker Image & Update Application Helm Chart Values'
on:
  push:
    branches:
      - main
env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
jobs:
  build_image:
    name: Build Image & Update Helm Chart Values
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    steps:
      # Install Node.js dependencies
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      # Login to Docker registry
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Install yq
      - name: Install yq 
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.12.0/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
          yq --version
      # Build and test application
      - name: Build, test and push to Docker Hub
        run: |
          echo Build started on `date`
          echo Run node.js tests...
          npm run test
          CONTAINER_IMAGE_TAG="$(node -e "console.log(require('./package.json').version);")"
          echo Building the Docker image...
          docker build -t ghcr.io/alex00pep/ecommerce-products:$CONTAINER_IMAGE_TAG . 
          echo Pushing the Docker image...
          docker push ghcr.io/alex00pep/ecommerce-products:$CONTAINER_IMAGE_TAG
      # Clone git repository with Helm charts, update and push changes
      - name: Update image tag in Helm git repo 
        run: | 
          CONTAINER_IMAGE_TAG="$(node -e "console.log(require('./package.json').version);")"
          echo "New container image tag: $CONTAINER_IMAGE_TAG"
          echo "Create temporary folder to clone the repo into..."
          TEMP_FOLDER="$(mktemp -d)" 
          echo Clone the repository...
          git clone -b main "https://alex00pep:${ACCESS_TOKEN}@github.com/alex00pep/microservice-example-helm-charts.git" ${TEMP_FOLDER} 
          cd ${TEMP_FOLDER}/application-charts/products 
          ls
          echo Update Helm chart values-dev with new image tag
          CONTAINER_IMAGE_TAG=$CONTAINER_IMAGE_TAG yq e -i '.products.deployment.imageTag = env(CONTAINER_IMAGE_TAG)' ./values-dev.yaml
          echo 'Container image tag updated in products/values-dev.yaml'           
          git config user.email "alexmtnezf@gmail.com" 
          git config user.name "Alexander Martinez Fajardo" 
          git add .
          git commit -m "refactor - updated Helm chart values for dev environment with container image - $CONTAINER_IMAGE_TAG" 
          git push -u origin main
